version: '3.9'

services:
  rabbit:
    build: env/
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_API_PORT}:15672"
    networks:
      rabbitmq:

networks:
  rabbitmq: